### ISSUE TITLE
final deployment gives Authentication Error

### ISSUE THREAD

**Issue by noamanag** [jandusek/twilio-phone-client#12]
on running npm run deploy after all other steps are completed for installation:

$ twilio-phone-client-main % npm run deploy

> phone-client@0.0.1 deploy /Users/noaman_sarguroh/Desktop/twilio-phone-client-main
> react-scripts build && rm -rf deploy/assets/ && mkdir deploy/assets/ && cp -r build/* deploy/assets/ && cd deploy && TWILIO_SERVERLESS_API_CONCURRENCY=1 twilio serverless:deploy

Creating an optimized production build...
Compiled successfully.

File sizes after gzip:

  252.45 KB  build/static/js/2.834e44f4.chunk.js
  18.13 KB   build/static/js/main.00cfe3ac.chunk.js
  779 B      build/static/js/runtime-main.a44a3e6c.js
  398 B      build/static/css/main.6fd2da93.chunk.css

The project was built assuming it is hosted at /.
You can control this with the homepage field in your package.json.

The build folder is ready to be deployed.
You may serve it with a static server:

  npm install -g serve
  serve -s build

Find out more about deployment here:

  bit.ly/CRA-deploy

Deploying functions & assets to the Twilio Runtime

Account         AC*****************************
Token           IkCG****************************
Service Name    twilio-phone-client
Environment     dev
Root Directory  /Users/noaman_sarguroh/Desktop/twilio-phone-client-main/deploy
Dependencies    twilio
Env Variables   API_KEY, API_SECRET, CHAT_SERVICE_SID, TWILIO_NUMBER, TWIML_APP_SID, SECRET, TWILIO_ACCOUNT_SID, TWILIO_AUTH_TOKEN
Runtime         undefined

✖ Failed Deployment

│ ERROR Failed API Request 20003
│ 
│ Authenticate
│ 
│ More info: https://www.twilio.com/docs/errors/20003

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! phone-client@0.0.1 deploy: `react-scripts build && rm -rf deploy/assets/ && mkdir deploy/assets/ && cp -r build/* deploy/assets/ && cd deploy && TWILIO_SERVERLESS_API_CONCURRENCY=1 twilio serverless:deploy`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phone-client@0.0.1 deploy script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/noaman_sarguroh/.npm/_logs/2021-05-07T08_51_29_636Z-debug.log

The full logs is as follows:
/Users/noaman_sarguroh/.npm/_logs/2021-05-07T08_51_29_636Z-debug.log:
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'deploy' ]
2 info using npm@6.14.12
3 info using node@v14.16.1
4 verbose run-script [ 'predeploy', 'deploy', 'postdeploy' ]
5 info lifecycle phone-client@0.0.1~predeploy: phone-client@0.0.1
6 info lifecycle phone-client@0.0.1~deploy: phone-client@0.0.1
7 verbose lifecycle phone-client@0.0.1~deploy: unsafe-perm in lifecycle true
8 verbose lifecycle phone-client@0.0.1~deploy: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/noaman_sarguroh/Desktop/twilio-phone-client-main/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin
9 verbose lifecycle phone-client@0.0.1~deploy: CWD: /Users/noaman_sarguroh/Desktop/twilio-phone-client-main
10 silly lifecycle phone-client@0.0.1~deploy: Args: [
10 silly lifecycle   '-c',
10 silly lifecycle   'react-scripts build && rm -rf deploy/assets/ && mkdir deploy/assets/ && cp -r build/* deploy/assets/ && cd deploy && TWILIO_SERVERLESS_API_CONCURRENCY=1 twilio serverless:deploy'
10 silly lifecycle ]
11 silly lifecycle phone-client@0.0.1~deploy: Returned: code: 1  signal: null
12 info lifecycle phone-client@0.0.1~deploy: Failed to exec deploy script
13 verbose stack Error: phone-client@0.0.1 deploy: `react-scripts build && rm -rf deploy/assets/ && mkdir deploy/assets/ && cp -r build/* deploy/assets/ && cd deploy && TWILIO_SERVERLESS_API_CONCURRENCY=1 twilio serverless:deploy`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1048:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid phone-client@0.0.1
15 verbose cwd /Users/noaman_sarguroh/Desktop/twilio-phone-client-main
16 verbose Darwin 19.5.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "deploy"
18 verbose node v14.16.1
19 verbose npm  v6.14.12
20 error code ELIFECYCLE
21 error errno 1
22 error phone-client@0.0.1 deploy: `react-scripts build && rm -rf deploy/assets/ && mkdir deploy/assets/ && cp -r build/* deploy/assets/ && cd deploy && TWILIO_SERVERLESS_API_CONCURRENCY=1 twilio serverless:deploy`
22 error Exit status 1
23 error Failed at the phone-client@0.0.1 deploy script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by jandusek** [comment]
I'd try checking you are using the correct CLI profile for the deployment by running `twilio profiles:list`.

If that did not solve the error, try adding the `--profile` flag with the name of your CLI profile to the `twilio serverless:deploy` command in [package.json](https://github.com/jandusek/twilio-phone-client/blob/main/package.json#L22).

It looks like sometimes the CLI profile credentials may be overwritten by the local .env credentials.

**Comment by noamanag** [comment]
> I'd try checking you are using the correct CLI profile for the deployment by running `twilio profiles:list`.
> 
> If that did not solve the error, try adding the `--profile` flag with the name of your CLI profile to the `twilio serverless:deploy` command in [package.json](https://github.com/jandusek/twilio-phone-client/blob/main/package.json#L22).
> 
> It looks like sometimes the CLI profile credentials may be overwritten by the local .env credentials.

Adding the profile flag in package.json worked, thanks a lot, just one query, will I able to implement whatsapp as a channel in this by updating the code, or will there be a need for anything external as well from twilio functions?

P.S: I have whatsapp enabled/verified on the same number

**Comment by jandusek** [comment]
If you just want to replace SMS with Whatsapp, that should be quite easy. You'll probably just need to modify these two backend functions to use WA instead of SMS:
https://github.com/jandusek/twilio-phone-client/blob/main/deploy/functions/msgInbound.protected.js
https://github.com/jandusek/twilio-phone-client/blob/main/deploy/functions/msgOutbound.js

If you want to add WA as a 2nd channel next to SMS, you'd need to make some UI changes as well that'd allow selecting between Whatsapp and SMS when starting a new thread and also some changes that'd allow both SMS and Whatsapp threads to the same number to coexist.

If you do make some progress on this, feel free to share a PR.

**Comment by noamanag** [comment]
Sure, will do, thanks again & keep up the great work!
